databases:
  - name: mysite
    databaseName: mysite
    user: mysite
    plan: starter

services:
  - type: web
    name: mysite
    runtime: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server -b 0.0.0.0 -p $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        value: "REDACTED_RAILS_MASTER_KEY"
      - key: GOOGLE_CLIENT_ID
        value: "REDACTED_GOOGLE_CLIENT_ID"
      - key: GOOGLE_CLIENT_SECRET
        value: "REDACTED_GOOGLE_CLIENT_SECRET"
      - key: WEB_CONCURRENCY
        value: 2 # sensible default

  - type: shell
    name: mysite-shell
    plan: starter
